<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanhiasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $init = [
            0 => ['batalhao_id' => 1,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            1 => ['batalhao_id' => 1,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            2 => ['batalhao_id' => 1,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            3 => ['batalhao_id' => 1,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            4 => ['batalhao_id' => 2,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            5 => ['batalhao_id' => 2,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            6 => ['batalhao_id' => 2,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            7 => ['batalhao_id' => 2,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            8 => ['batalhao_id' => 3,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            9 => ['batalhao_id' => 3,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            10 => ['batalhao_id' => 3,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            11 => ['batalhao_id' => 3,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            12 => ['batalhao_id' => 4,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            13 => ['batalhao_id' => 4,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            14 => ['batalhao_id' => 4,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            15 => ['batalhao_id' => 4,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            16 => ['batalhao_id' => 5,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            17 => ['batalhao_id' => 5,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            18 => ['batalhao_id' => 5,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            19 => ['batalhao_id' => 5,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            20 => ['batalhao_id' => 6,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            21 => ['batalhao_id' => 6,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            22 => ['batalhao_id' => 6,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            23 => ['batalhao_id' => 6,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            24 => ['batalhao_id' => 7,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            25 => ['batalhao_id' => 7,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            26 => ['batalhao_id' => 7,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            27 => ['batalhao_id' => 7,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            28 => ['batalhao_id' => 8,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            29 => ['batalhao_id' => 8,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            30 => ['batalhao_id' => 8,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            31 => ['batalhao_id' => 8,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            32 => ['batalhao_id' => 9,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            33 => ['batalhao_id' => 9,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            34 => ['batalhao_id' => 9,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            35 => ['batalhao_id' => 9,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            36 => ['batalhao_id' => 10,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            37 => ['batalhao_id' => 10,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            38 => ['batalhao_id' => 10,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            39 => ['batalhao_id' => 10,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            40 => ['batalhao_id' => 11,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            41 => ['batalhao_id' => 11,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            42 => ['batalhao_id' => 11,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            43 => ['batalhao_id' => 11,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            44 => ['batalhao_id' => 12,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            45 => ['batalhao_id' => 12,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            46 => ['batalhao_id' => 12,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            47 => ['batalhao_id' => 12,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            48 => ['batalhao_id' => 13,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            49 => ['batalhao_id' => 13,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            50 => ['batalhao_id' => 13,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            51 => ['batalhao_id' => 13,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            52 => ['batalhao_id' => 14,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            53 => ['batalhao_id' => 14,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            54 => ['batalhao_id' => 14,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            55 => ['batalhao_id' => 14,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            56 => ['batalhao_id' => 15,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            57 => ['batalhao_id' => 15,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            58 => ['batalhao_id' => 15,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            59 => ['batalhao_id' => 15,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            60 => ['batalhao_id' => 16,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            61 => ['batalhao_id' => 16,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            62 => ['batalhao_id' => 16,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            63 => ['batalhao_id' => 16,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            64 => ['batalhao_id' => 17,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            65 => ['batalhao_id' => 17,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            66 => ['batalhao_id' => 17,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            67 => ['batalhao_id' => 17,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            68 => ['batalhao_id' => 18,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            69 => ['batalhao_id' => 18,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            70 => ['batalhao_id' => 18,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            71 => ['batalhao_id' => 18,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            72 => ['batalhao_id' => 19,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            73 => ['batalhao_id' => 19,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            74 => ['batalhao_id' => 19,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            75 => ['batalhao_id' => 19,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            76 => ['batalhao_id' => 20,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            77 => ['batalhao_id' => 20,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            78 => ['batalhao_id' => 20,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            79 => ['batalhao_id' => 20,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            80  => ['batalhao_id' => 21,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            81 => ['batalhao_id' => 21,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            82 => ['batalhao_id' => 21,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            83 => ['batalhao_id' => 21,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            84 => ['batalhao_id' => 22,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            85 => ['batalhao_id' => 22,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            86 => ['batalhao_id' => 22,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            87 => ['batalhao_id' => 22,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            88 => ['batalhao_id' => 23,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            89 => ['batalhao_id' => 23,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            90 => ['batalhao_id' => 23,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            91 => ['batalhao_id' => 23,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            92 => ['batalhao_id' => 24,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            93 => ['batalhao_id' => 24,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            94 => ['batalhao_id' => 24,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            95 => ['batalhao_id' => 24,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
            96 => ['batalhao_id' => 25,'nome' => '1º Companhia', 'abreviatura' => '1º CIA'],
            97 => ['batalhao_id' => 25,'nome' => '2º Companhia', 'abreviatura' => '2º CIA'],
            98 => ['batalhao_id' => 25,'nome' => '3º Companhia', 'abreviatura' => '3º CIA'],
            99 => ['batalhao_id' => 25,'nome' => '4º Companhia', 'abreviatura' => '4º CIA'],
        ];
        DB::table('companhias')->insert($init);
    }
}
